apiVersion: apps/v1
kind: Deployment
metadata:
  name: jira-ai-bot
  namespace: jira-bot

spec:
  replicas: 1

  selector:
    matchLabels:
      app: jira-ai-bot

  template:
    metadata:
      labels:
        app: jira-ai-bot

    spec:
      imagePullSecrets:
      - name: dockerhub-secret

      containers:
      - name: bot
<<<<<<< HEAD
        image: huektyc/jira-ai-bot:d2c6c38
=======
        image: huektyc/jira-ai-bot:init
>>>>>>> 1fb5ca9 (correction of the previous one)

        envFrom:
        - secretRef:
            name: jira-bot-secret
